[AD-721] move clang-check after cppcheck

diff --git a/.github/workflows/linux-build.yml b/.github/workflows/linux-build.yml
--- a/.github/workflows/linux-build.yml
+++ b/.github/workflows/linux-build.yml
@@ -54,6 +54,13 @@ jobs:
       with:
         name: cppcheck-results
         path: cppcheck-results.log
+    
+    - name: clang-tidy-check
+      uses: ZedThree/clang-tidy-review@v0.8.3
+      id: review
+      # If there are any comments, fail the check
+    - if: steps.review.outputs.total_comments > 0
+      run: exit 1
   
     - name: Extract key-pair into file
       run: |
@@ -142,13 +149,6 @@ jobs:
         check_name: "Ubuntu 20.04 Build Unit Test Results Check"
         comment_title: "Ubuntu 20.04 Build Unit Test Results"
         files: ./odbc_test_result.xml
-
-    - name: clang-tidy-check
-      uses: ZedThree/clang-tidy-review@v0.8.3
-      id: review
-      # If there are any comments, fail the check
-    - if: steps.review.outputs.total_comments > 0
-      run: exit 1
   
   build-linux-docker-image:
     runs-on: ubuntu-20.04
