[AD-1070] Removed unnecessary comments. Attempting to sign within the windows build.

diff --git a/.github/workflows/win-build.yml b/.github/workflows/win-build.yml
--- a/.github/workflows/win-build.yml
+++ b/.github/workflows/win-build.yml
@@ -9,6 +9,13 @@ on:
     branches:
       - main
       - develop
+  workflow_dispatch:
+    inputs:
+      sign:
+        description: Shall ign Artifacts (for release only)
+        type: boolean
+        required: false
+        default: false
 
 env:
   CI_OUTPUT_PATH: "ci-output"
@@ -62,6 +69,14 @@ jobs:
     needs: trufflehog-git-secrets-scan
     steps:
     - uses: actions/checkout@v2
+    - uses: aws-actions/configure-aws-credentials@v1
+      with:
+        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        aws-region: us-west-2
+        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
+        role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
+        role-duration-seconds: 900
     # TODO Reactivate cppcheck
     # https://bitquill.atlassian.net/browse/AD-752
     # - name: setup-cppcheck
@@ -172,6 +187,47 @@ jobs:
       env:
         OPENSSL_ROOT_DIR: '${{ env.VCPKG_ROOT }}/packages/openssl_x86-windows'
 
+    - name: Sign Executables
+      run: |
+        
+        if ${{ github.event.inputs.sign && github.event.inputs.sign != 'false'}}
+        then
+          echo "Signing is enabled. Will attempt to sign"
+        
+          # Upload unsigned .exe to S3 Bucket
+          version_id=$( aws s3api put-object --bucket ${{ secrets.AWS_UNSIGNED_BUCKET }} --key ${{ secrets.AWS_KEY }} --body build/odbc/cmake/Release/docdb-odbc-driver-x86-${{env.ODBC_DRIVER_VERSION}}-all.exe  --acl bucket-owner-full-control | jq '.VersionId' )
+          job_id=""
+          # Attempt to get Job ID from bucket tagging, will retry up to 3 times before exiting with a failure code.
+          # Will sleep for 5 seconds between retries.
+          for (( i=0; i<3; i++ ))
+          do  
+            # Get job ID
+            id=$( aws s3api get-object-tagging --bucket ${{ secrets.AWS_UNSIGNED_BUCKET }} --key ${{ secrets.AWS_KEY }} --version-id ${version_id} | jq -r '.TagSet[0].Value' )
+            if [ $id != "null" ]
+            then
+              job_id=$id
+              break
+            fi
+        
+            sleep 5s
+          done
+        
+             if [[ $job_id = "" ]]
+          then
+             echo "Exiting because unable to retrieve job ID"
+             exit 1
+          fi
+        
+          # Poll signed S3 bucket to see if the signed artifact is there
+          aws s3api wait object-exists --bucket ${{ secrets.AWS_SIGNED_BUCKET }} --key ${{ secrets.AWS_KEY }}-${job_id}
+        
+          # Get signed DLL from S3
+          aws s3api get-object --bucket ${{ secrets.AWS_SIGNED_BUCKET }} --key ${{ secrets.AWS_KEY }}-${job_id} build/odbc/cmake/Release/docdb-odbc-driver-x86-${{env.ODBC_DRIVER_VERSION}}-all-signed.exe
+
+        else
+          echo "Signing will be skipped"
+        fi
+
     - name: Upload ODBC driver build at push to develop
       if: ${{env.SHOULD_CREATE_ARTIFACTS == 'true'}} 
       uses: actions/upload-artifact@v3
@@ -258,6 +314,14 @@ jobs:
     needs: trufflehog-git-secrets-scan
     steps:
     - uses: actions/checkout@v2
+    - uses: aws-actions/configure-aws-credentials@v1
+      with:
+        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        aws-region: us-west-2
+        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
+        role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
+        role-duration-seconds: 900
     # TODO Reactivate cppcheck
     # https://bitquill.atlassian.net/browse/AD-752
     # - name: run-cppcheck
@@ -353,6 +417,47 @@ jobs:
         .\build_win_release64.ps1
       env:
         OPENSSL_ROOT_DIR: '${{env.VCPKG_ROOT}}/packages/openssl_x64-windows'
+
+    - name: Sign Executables
+      run: |
+        
+        if ${{ github.event.inputs.sign && github.event.inputs.sign != 'false'}}
+        then
+          echo "Signing is enabled. Will attempt to sign"
+        
+          # Upload unsigned .exe to S3 Bucket
+          version_id=$( aws s3api put-object --bucket ${{ secrets.AWS_UNSIGNED_BUCKET }} --key ${{ secrets.AWS_KEY }} --body build/odbc/cmake/Release/docdb-odbc-driver-amd64-${{env.ODBC_DRIVER_VERSION}}-all.exe  --acl bucket-owner-full-control | jq '.VersionId' )
+          job_id=""
+          # Attempt to get Job ID from bucket tagging, will retry up to 3 times before exiting with a failure code.
+          # Will sleep for 5 seconds between retries.
+          for (( i=0; i<3; i++ ))
+          do  
+            # Get job ID
+            id=$( aws s3api get-object-tagging --bucket ${{ secrets.AWS_UNSIGNED_BUCKET }} --key ${{ secrets.AWS_KEY }} --version-id ${version_id} | jq -r '.TagSet[0].Value' )
+            if [ $id != "null" ]
+            then
+              job_id=$id
+              break
+            fi
+          
+            sleep 5s
+          done
+          
+             if [[ $job_id = "" ]]
+          then
+             echo "Exiting because unable to retrieve job ID"
+             exit 1
+          fi
+          
+          # Poll signed S3 bucket to see if the signed artifact is there
+          aws s3api wait object-exists --bucket ${{ secrets.AWS_SIGNED_BUCKET }} --key ${{ secrets.AWS_KEY }}-${job_id}
+          
+          # Get signed DLL from S3
+          aws s3api get-object --bucket ${{ secrets.AWS_SIGNED_BUCKET }} --key ${{ secrets.AWS_KEY }}-${job_id} build/odbc/cmake/Release/docdb-odbc-driver-amd64-${{env.ODBC_DRIVER_VERSION}}-all-signed.exe
+
+        else
+          echo "Signing will be skipped"
+        fi
 
     - name: Upload ODBC driver build at push to develop
       if: ${{env.SHOULD_CREATE_ARTIFACTS == 'true'}}
